backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "portfolio"
    label: "نمونه کارها"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "عنوان پروژه", name: "title", widget: "string"}
      - {label: "توضیحات", name: "description", widget: "text"}
      - {label: "تصویر", name: "image", widget: "image"}
      - {label: "لینک پروژه", name: "link", widget: "string", required: false}
